export const chatCopy = {
  title: 'FlowChat.一阅即散',
  description: '房间码为四位数字，房间创建1小时或所有人退出后自动失效',
  createRoom: '新建房间',
  creatingRoom: '创建中...',
  joinRoom: '加入房间',
  joiningRoom: '加入中...',
  roomCodeLabel: '房间码（4 位数字）',
  roomCodeShortLabel: '房间码',
  roomCodePlaceholder: '0000',
  invalidRoomCode: '请输入 4 位数字房间码',
  connecting: '正在连接...',
  connectionHealthy: '实时连接正常',
  connectionRetrying: '实时连接异常，正在重试...',
  connectionTimedOut: '连接超时，正在重试...',
  roomExpiredStatus: '房间已到期',
  roomExpiredError: '房间已到期，记录已销毁，不能再发送消息',
  roomUnavailable: '房间不可用',
  roomNotFound: '房间不存在或已过期',
  returnLabel: '返回',
  backToChat: '返回流式聊天',
  enteringRoom: '正在进入房间',
  copyFailed: '复制失败，请手动复制',
  copied: '已复制',
  remainingPrefix: '剩余',
  exitRoom: '退出',
  exitingRoom: '退出中...',
  messagesEmpty: '暂无消息，开始聊天吧。',
  anonymousUser: '匿名用户',
  nicknameTitle: '设置聊天昵称',
  nicknameDescription: '昵称仅在当前房间显示，不会暴露账号身份信息。',
  nicknamePlaceholder: '请输入 1-20 字昵称',
  nicknameRequired: '请先设置昵称',
  nicknameInvalid: '昵称需为 1-20 个字符，且不能全为空格',
  savingNickname: '保存中...',
  confirmEnter: '确认进入',
  send: '发送',
  sending: '发送中...',
  sendPlaceholder: '输入消息，Enter 发送',
  sendDisabledPlaceholder: '房间已到期，无法发送消息',
  messageInvalid: '消息需为 1-500 个字符，且不能全为空格',
  nicknamePrefix: '昵称：',
  nicknameMissing: '未设置昵称',
  invalidPathTitle: '聊天路径无效',
  invalidPathDescription: '请通过 `/chat` 进入并创建/加入房间。',
};
